// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	category "vidlearn-final-projcect/business/category"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: _a0
func (_m *Repository) CreateCategory(_a0 *category.Category) (*category.Category, error) {
	ret := _m.Called(_a0)

	var r0 *category.Category
	if rf, ok := ret.Get(0).(func(*category.Category) *category.Category); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*category.Category) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategory provides a mock function with given fields: ID
func (_m *Repository) DeleteCategory(ID int) (*category.Category, error) {
	ret := _m.Called(ID)

	var r0 *category.Category
	if rf, ok := ret.Get(0).(func(int) *category.Category); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCategory provides a mock function with given fields:
func (_m *Repository) GetAllCategory() ([]*category.Category, error) {
	ret := _m.Called()

	var r0 []*category.Category
	if rf, ok := ret.Get(0).(func() []*category.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*category.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ID
func (_m *Repository) GetCategoryByID(ID int) (*category.Category, error) {
	ret := _m.Called(ID)

	var r0 *category.Category
	if rf, ok := ret.Get(0).(func(int) *category.Category); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: categoryCurrent, IDCurrent
func (_m *Repository) UpdateCategory(categoryCurrent *category.Category, IDCurrent int) (*category.Category, error) {
	ret := _m.Called(categoryCurrent, IDCurrent)

	var r0 *category.Category
	if rf, ok := ret.Get(0).(func(*category.Category, int) *category.Category); ok {
		r0 = rf(categoryCurrent, IDCurrent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*category.Category, int) error); ok {
		r1 = rf(categoryCurrent, IDCurrent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t testing.TB) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
